config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'games#new'
  get 'new', to: 'games#new'
  post 'score', to: 'games#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require "open-uri"

class GamesController < ApplicationController
  def new
    @letters = Array.new(10) { ('a'..'z').to_a.sample }
  end

  def score
    @api_response = JSON.parse(URI.open("https://wagon-dictionary.herokuapp.com/#{params[:word]}").read)
    @word_exists = @api_response["found"]

    # @contains_letters = true
    # params[:word].split("").each do |char|
    #   @contains_letters = params[:letters].include?(char)
    #   break unless @contains_letters
    # end

    @contains_letters = params[:word].split('').all? { params[:letters].include?(_1) }

    @has_won = @word_exists && @contains_letters
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>

<div class="letters">
  <% @letters.each do |letter| %>
    <h3><%= letter %></h3>
  <% end %>
</div>

<p>Type the longest word you can find with these letters</p>
<form action="<%= score_path %>" method="POST">
  <input type="text"
         name="word"
         placeholder="Type your word!">
  <input type="submit" value="Done!">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <% @letters.each do |letter| %>
    <input type="hidden" name="letters[]" value="<%= letter %>" >
  <% end %>

</form>

app/views/games/score.html.erb
<h1>Score</h1>

<% if @has_won %>
<p> You win! </p>
<% else %>
<p> You lose! </p>
<% end %>

<div class="play_again"><%= link_to "Play again?", new_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>